### ISSUE TITLE
elasticsearch component links in multiple versions of CPR

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_capability_indexing#122]
... potentially causing SIGSEGV instead of a successful elasticsearch indexing operation.
   * `seznam/elasticlient` has a dependency on `libcpr/cpr`.
   * iRODS' elasticlient now imports a submodule which is a more recent libcpr than our externals provide
   * Most likely we just need to ignore (as in "not link to") irods-externals-cpr1.3.0-X because that dependency's

The solution was discovered via this client example using the irods externals
```
#include <vector>
#include <elasticlient/client.h>
#include <cpr/api.h>
#include <cpr/response.h>
#include <iostream>

int main(){
        using HTTPMethod = elasticlient::Client::HTTPMethod;
        using namespace std;

        elasticlient::Client cl { std::vector<std::string>{"http://localhost:9100/" } };
        cpr::Response a;
        a = cl.performRequest ( HTTPMethod::PUT,  "metadata/_doc/2", R"(
                {
                        "fileName": "goodbye"
                }       
        )");
        cout << "code\t" << a.status_code << "\n";
        cout << "text\t" << a.text << "\n";
}
```
The build script is here:
```
ELASTICLI=/opt/irods-externals/elasticlientd68e30e3-0

# ELASTICLI=/opt/irods-externals/elasticlient0.1.0-2

CPR=/opt/irods-externals/cpr1.3.0-1

/opt/irods-externals/clang13.0.0-0/bin/clang++ -stdlib=libc++ $1 \
 -Wl,-rpath,/opt/irods-externals/clang-runtime13.0.0-0/lib:$CPR/lib:$ELASTICLI/lib \
 -I $ELASTICLI/include -L $ELASTICLI/lib \
 -I $CPR/include \
 /opt/irods-externals/cpr1.3.0-1/lib/libcpr.so \
 -l elasticlient -l cpr 
```
With the absolute path of .../cpr1.3.0-1/lib/... included, the compiled a.out caused a SIGSEGV .  With that line deleted, a.out performed to its desired purpose.

**Comment by korydraughn** [comment]
This work appears to have been completed.

Closing.
