### ISSUE TITLE
Plugins can throw exception when loading configuration

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_capability_indexing#135]
## Bug Report
If a plugin fails to load a config file and throws an exception, the start function needs to catch it and convert the exception to a proper irods::error object and return it.

https://github.com/irods/irods_capability_indexing/blob/82eee54b7433fdb51df43da8776d962b82185147/libirods_rule_engine_plugin-elasticsearch.cpp#L599

Plugins must not be allowed to throw exceptions across shared library boundaries.

**Comment by trel** [comment]
Is this something that ALL plugins need to do better?

**Comment by korydraughn** [comment]
Absolutely.

**Comment by trel** [comment]
Okay, so definitely update that template as well...
