### ISSUE TITLE
More versions of irods should be supported

### ISSUE THREAD

**Issue by bh9** [irods/irods_capability_indexing#14]
https://github.com/irods/irods_capability_indexing/blob/8aa3caede5e1d25b531b166716b8beaecb486fd8/CMakeLists.txt#L4
The only version this will work on is 4.3.0, this seems quite limited. I've modified the line to see if it will at least build on 4.2.7

**Comment by trel** [comment]
The 4-2-stable branch is in the pipeline to be released with 4.2.8 - there are dependencies in externals that still need to be pushed/packaged.

**Comment by bh9** [comment]
Part of this issue was to point out that `EXACT REQUIRED` means it won't work with e.g. 4.3.1 either.  
Also, I note that 4-2-stable currently says 4.2.6, so would I be right to assume that 4.2.7 should theoretically work?

**Comment by trel** [comment]
it built at the time with 4.2.6 - we have not yet released this plugin.

**Comment by trel** [comment]
closing - we're getting things squared up for 4.2.7 and 4.2.8 now.
