### ISSUE TITLE
`example_indexing_invocation.r` contains storage tiering logic instead of indexing logic

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_capability_indexing#140]
The following file needs to be updated for this repo or removed entirely.
https://github.com/irods/irods_capability_indexing/blob/3f3529dea01c883f4e6c691108878fef0930a634/example_indexing_invocation.r#L1-L9

**Comment by trel** [comment]
oh, yeah, that's just wrong.

**Comment by korydraughn** [comment]
This file should be removed given the fact that nothing relies on it and the slide deck doesn't provide notes about invoking indexing operations manually.
