### ISSUE TITLE
Install of outdated externals in build hook breaks builds

### ISSUE THREAD

**Issue by FifthPotato** [irods/irods_capability_indexing#162]
- [x] main
- [x] 4-3-stable

---

On ubuntu24. This is likely due to the outdated externals not being available in the repo, so trying to build it with the dev environment won't work.

Lines:
https://github.com/irods/irods_capability_indexing/blob/6ea172ce0f33c310831d108d251aafa71906c75b/irods_consortium_continuous_integration_build_hook.py#L18-L20

To get them to work locally, I replaced these with 
```
        'irods-externals-boost-libcxx1.81.0-1',
        'rods-externals-clang-runtime13.0.1-0',
        'irods-externals-clang13.0.1-0'
```
Does this need to be changed on a per-OS basis? Or should this work for all of them?

**Comment by alanking** [comment]
The same externals packages should be used to build all packages for all platforms for a particular version. Therefore, the externals should not differ from OS to OS. We should update them to use the same externals as those being used by other plugins and the iRODS server (where applicable). For any externals which are specific to this plugin, we should find the latest one available and use that, if possible.

**Comment by alanking** [comment]
@FifthPotato - Please checkbox and close if complete. Thanks
