### ISSUE TITLE
Units field of AVU should read "elasticsearch" for that technology

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_capability_indexing#20]
- [x] master
- [x] 4-2-stable

**Comment by d-w-moore** [comment]
Currently AVU's are matched for a units field of "elastic" instead.

**Comment by d-w-moore** [comment]
Now testing this and other fixes in 4-2-stable and 4.2.7 release versions, in CentOS7, from respective points on this [branch](https://github.com/d-w-moore/irods_capability_indexing/tree/23.42s.cbnr_bump) Will click 4-2-stable box done when those tests have passed.

**Comment by trel** [comment]
don't click the checkbox here until a PR has been merged onto 4-2-stable
