### ISSUE TITLE
Include metadata added to collections

### ISSUE THREAD

**Issue by kript** [irods/irods_capability_indexing#42]
- [x] master
- [x] 4-2-stable
-----

Might be related to #19 but with the deployment out of the box, and with indexing set on the top level collection of a zone, we are finding that adding metadata to a collection is not populating the elastic search database. 
Is this intentional, or have we missed a configuration, or is adding collection metadata a WIP/ something we'd need to raise a feature request for?

Our use case is that we have collections with hundreds, perhaps thousands of files underneath, sometimes in sub-collections and we apply the metadata at the collection level so we don't need to apply it separately to all the files, also making the updating of that metadata trivial and atomic. 

thanks,

John

**Comment by trel** [comment]
It should not be a WIP - this is expected to work as you describe.   Will work to reproduce.

**Comment by kript** [comment]
Did you have any success reproducing it?

**Comment by trel** [comment]
Not upon initial attempt - timeframe is realistically a week or so out before we try again.

**Comment by trel** [comment]
Meant to write earlier... we've confirmed this is not currently implemented.   Will be added in the next cycle.
