### ISSUE TITLE
AVUs not purged for  data objects when deleted

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_capability_indexing#46]
In the current release of the indexing plugin, removed data objects undergo a full text purge operation, but not an AVU purge.

**Comment by trel** [comment]
is this covered now in the recent commits?   if so, let's point to one/two and close it.

**Comment by d-w-moore** [comment]
I must have made this redundantly .  Yes, this is covered in the recent commits.  Do we point each at the other one and close both, then?

**Comment by d-w-moore** [comment]
Redundant with #37
