### ISSUE TITLE
Reasonable default for job_limits

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_capability_indexing#88]
- [x] main
- [x] 4-2-stable
---
Set the configuration variable `job_limit_per_collection_indexing_operation` to a reasonable concrete default, such as "1000".
(1000 might be a comfortable default because it is greater than the number of available CPUs to process delayed tasks, but will not allow reasonable usage to exhaust available memory on the iRODS server.

**Comment by d-w-moore** [comment]
This is  being put into effect as of #111 .  Not just because this is a convenient place and overlapping concern for such a change, but in possible preparation for resolving #107 (rationale: if an AVU annotation change can cause an existing collection operation to reset its iteration back to square zero, it's best not to have a virtually unlimited number of jobs remaining in the queue).

**Comment by alanking** [comment]
Please close if done, @d-w-moore
