### ISSUE TITLE
Some JSON configuration parameters are strings, but could be integers

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_indexing#91]
- [x] main
- [x] 4-2-stable
---
The following options are strings in the JSON configuration and are interpreted as signed and unsigned integers:
 - `job_limit_per_collection_indexing_operation` (unsigned int)
 - `minimum_delay_time` (int)
 - `maximum_delay_time` (int)

We should probably just accept an integer in the JSON. Please investigate whether this is possible. In particular, make sure `job_limit_per_collection_indexing_operation` won't overflow or underflow.

**Comment by alanking** [comment]
Consider adding units to the names as well (e.g. `minimum_delay_time_in_seconds`?)

**Comment by trel** [comment]
we'd have to make sure old/existing strings are also honored, but superseded by the new/correct configs.

**Comment by alanking** [comment]
> Consider adding units to the names as well (e.g. `minimum_delay_time_in_seconds`?)

Unless we are still considering doing this?

**Comment by korydraughn** [comment]
Let's create a new issue for the renaming of config settings. That way, the PRs addressing this issue can be merged.

**Comment by d-w-moore** [comment]
ok , I support that. Will make the new issue.

**Comment by d-w-moore** [comment]
> The following options are strings in the JSON configuration and are interpreted as signed and unsigned integers:
> 
> * `job_limit_per_collection_indexing_operation` (unsigned int)
> * `minimum_delay_time` (int)
> * `maximum_delay_time` (int)
> 
> We should probably just accept an integer in the JSON. Please investigate whether this is possible. In particular, make sure `job_limit_per_collection_indexing_operation` won't overflow or underflow.

#114 is the new issue for this concern.

**Comment by alanking** [comment]
I have checked the boxes. Leaving to @d-w-moore to close if done.

**Comment by d-w-moore** [comment]
Hmm, I don't seem to have a close option...

**Comment by alanking** [comment]
And what about now? :)

**Comment by d-w-moore** [comment]
Yes, thanks! Closing....
