### ISSUE TITLE
job_limit_per_collection_indexing_operation parameter wrongly described

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_capability_indexing#97]
- [x] main
- [x] 4-2-stable
---
The indexing configuration variable "job_limit_per_collection_indexing_operation" is incorrectly described in the README as a   "limit to number of concurrent collection operations ."

This is in error, since the parameter actually specifies a threshold to the number of delayed tasks maintained at any given time within  any **one** collection operation

**Comment by d-w-moore** [comment]
Also (ok, this issue should have been named "correct everything wrong with the README)... 
   * bulk_count should have  "integer" type, not "string".

**Comment by alanking** [comment]
Please close if done, @d-w-moore
